### PR TITLE
Updated models.py to use timezone safe datetime

### PR DESCRIPTION
**Pull request by robcharlwood**
Updated models.py to use timezone safe datetime in django if available, otherwise fallback to the standard datetime. Maintains backwards compatibility with Django 1.3.

### CODE REVIEW

**Comment by powellc** [comment]
Awesome. I'll review after the 4th of July cookout today ;) Thanks so much for your contributions.

**Comment by robcharlwood** [comment]
Many thanks @powellc :)

**Comment by powellc** [comment]
@robcharlwood Thanks again! Great patch.

**Comment by robcharlwood** [comment]
@powellc My pleasure, thanks for merging! :)

**Pull request merged**
